import React from 'react';
import $ from 'jquery';
import SessionExercise from './SessionExercise';

var divStyle = {
  border: "3px solid green",
  padding: "10px"
};

class Entry extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      title: "",
      comment: "",
      exercises: [
        {id: Date.now(), name: "From Constructor" }
      ]
    }
  }

  handleTitleChange = e => {
    this.setState({title: e.target.value});
  };
  handleCommentChange = e => {
    this.setState({comment: e.target.value});
  };
  handleSubmit = e => {
    e.preventDefault();
    var title = this.state.title.trim();
    var comment = this.state.comment.trim();
    if (!title || !comment) {
      console.log("fields not filled");
      return;
    }
    this.onEntrySubmit({title: title, comment: comment});
    this.setState({title: '', comment: ''});
  };

  onEntrySubmit = (entry) => {
    var entries = this.state.data || "";
    // Optimistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    entry.id = Date.now();
    var newEntries = entries.concat([entry]);
    this.setState({data: newEntries});
    $.ajax({
      url: '/data2/entries', //this.props.url,
      dataType: 'json',
      type: 'POST',
      data: entry,
      success: function (data) {
        this.setState({data: data});
      }.bind(this),
      error: function (xhr, status, err) {
        this.setState({data: entries});
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  };

  addExercise = () => {
    var newExercises = this.state.exercises.concat([{id:Date.now(), name:"From Button" + Date.now()}]);
    this.setState({exercises: newExercises});
  };

  /** manipulates state directly :/ */
  deleteExercise = (e) => { // event is the parameter
    e.preventDefault();
    var exerciseIndex = parseInt(e.target.value, 10);
    console.log("ex Index: " + exerciseIndex);
    this.setState( state => {
      state.exercises.splice(exerciseIndex, 1);
      return {exercises: state.exercises};
    });

  };

  render() {
    var exercises = this.state.exercises.map( (ex, exIndex) => {
      return <SessionExercise key={exIndex} exerciseName={ex.name}
                              deleteExercise={this.deleteExercise}
                              valuex={exIndex} />
    });
    return (
      <div id="entryform" style={divStyle}>
        <i>Entry</i>
        <h2>New Entry</h2>
        <button onClick={this.addExercise}>Add v Class</button>
        <form onSubmit={this.handleSubmit}>
          <input
            type="text"
            placeholder="Title"
            value={this.state.title}
            onChange={this.handleTitleChange}
          />
          <input
            type="text"
            placeholder="Comment"
            value={this.state.comment}
            onChange={this.handleCommentChange}
          />

          {exercises}

          <input type="submit" value="Post"/>
        </form>
      </div>
    );
  }
}

export default Entry;